### ISSUE TITLE
Add Parity bit output

### ISSUE THREAD

**Issue by evilmog** [1944GPW/ptap2dxf#1]
How hard would it be to add parity bits, an example is paper tape like the images attached, this is for the cyphercon badge which had a paper tape reader:
![D4JfZWfX4AAW6-Y](https://user-images.githubusercontent.com/3283026/56323181-50946780-6128-11e9-8e5c-a21f636d705f.jpg)

Codes used:
0102020001WIRE2 B0B05FACE8BADF00D50319
0102000001WIRE2 FEADC0ED5CAFEBEEF50319
0102030001WIRE1 0123456789ABCDEF010319

**Comment by 1944GPW** [comment]
G'day Dustin,
   I don't quite follow your 'codes used' lines sorry, and no images were attached, and I
don't have a badge.
Are you talking about a switch option to make the high bit (leftmost hole) a parity bit for the other seven?
That shouldn't be too hard to do, from first glance.
Regards,

Steve.




---------------------------- Original Message ----------------------------
Subject: [1944GPW/ptap2dxf] Add Parity bit output (#1)

**Comment by 1944GPW** [comment]
Dustin,
   I've just committed version 1.1 which has a new switch: parity={NONE,EVEN,ODD}. This uses the MSB (leftmost hole) for the bit. I've updated the doc to suit. I hope that's what you were after?
eg.
```
 $ dotnet ptap2dxf.dll --text="ABCD"
+---------+
| O   .  O|
| O   . O |
| O   . OO|
| O   .O  |
+---------+
Joiner 0000: data byte 00000000  absolute position 00000004
 $ dotnet ptap2dxf.dll --text="ABCD" --parity=even
+---------+
| O   .  O|
| O   . O |
|OO   . OO|
| O   .O  |
+---------+
Joiner 0000: data byte 00000000  absolute position 00000004
 $ dotnet ptap2dxf.dll --text="ABCD" --parity=odd
+---------+
|OO   .  O|
|OO   . O |
| O   . OO|
|OO   .O  |
+---------+
Joiner 0000: data byte 00000000  absolute position 00000004
 $
```
Steve.

**Comment by evilmog** [comment]
That is perfect!
